# Generated by Django 5.0 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block", models.CharField(max_length=10)),
                ("floor", models.IntegerField()),
                ("cell_x", models.IntegerField()),
                ("cell_y", models.IntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("wifi", "WiFi"), ("mobile", "Mobile")],
                        default="wifi",
                        max_length=10,
                    ),
                ),
                ("network_name", models.CharField(blank=True, max_length=100)),
                ("signal_strength", models.IntegerField(help_text="Signal strength in dBm")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["block", "floor", "mode"], name="heatmap_scan_block_f_c4a8fc_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["cell_x", "cell_y"], name="heatmap_scan_cell_x_ef1f9b_idx"),
        ),
    ]
