# Generated by Codex on 2026-03-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heatmap", "0004_block_floorplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="floorplan",
            name="blocked_cells",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="CellAggregate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("block", models.CharField(max_length=10)),
                ("floor", models.IntegerField()),
                ("cell_x", models.IntegerField()),
                ("cell_y", models.IntegerField()),
                ("cell_id", models.IntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("wifi", "WiFi"), ("mobile", "Mobile")],
                        default="wifi",
                        max_length=10,
                    ),
                ),
                ("service_provider", models.CharField(blank=True, max_length=60)),
                ("is_all_providers", models.BooleanField(default=False)),
                ("median_signal", models.FloatField()),
                ("scan_count", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["block", "floor", "cell_y", "cell_x"],
            },
        ),
        migrations.AddConstraint(
            model_name="cellaggregate",
            constraint=models.UniqueConstraint(
                fields=(
                    "block",
                    "floor",
                    "cell_x",
                    "cell_y",
                    "mode",
                    "service_provider",
                    "is_all_providers",
                ),
                name="uniq_cellaggregate_key",
            ),
        ),
        migrations.AddIndex(
            model_name="cellaggregate",
            index=models.Index(fields=["block", "floor", "mode", "is_all_providers"], name="heatmap_cel_block_52f0bb_idx"),
        ),
        migrations.AddIndex(
            model_name="cellaggregate",
            index=models.Index(fields=["cell_x", "cell_y"], name="heatmap_cel_cell_x_03b6b7_idx"),
        ),
    ]
