# Generated by Codex on 2026-04-01

from django.conf import settings
from django.db import migrations, models


def _get_dims(floor_number):
    floor_dimensions = getattr(settings, "HEATMAP_FLOOR_DIMENSIONS", {})
    raw_dims = floor_dimensions.get(floor_number) or floor_dimensions.get(str(floor_number)) or {}
    rows = int(raw_dims.get("rows", getattr(settings, "HEATMAP_GRID_ROWS", 12)))
    cols = int(raw_dims.get("cols", getattr(settings, "HEATMAP_GRID_COLS", 8)))
    return {"rows": max(1, rows), "cols": max(1, cols)}


def forward_fill_floor_plans(apps, schema_editor):
    Block = apps.get_model("heatmap", "Block")
    FloorPlan = apps.get_model("heatmap", "FloorPlan")
    Scan = apps.get_model("heatmap", "Scan")
    CellAggregate = apps.get_model("heatmap", "CellAggregate")

    block_cache = {block.code: block for block in Block.objects.all()}
    floor_cache = {}

    def get_floor_plan(block_code, floor_number):
        key = (block_code, floor_number)
        if key in floor_cache:
            return floor_cache[key]
        block = block_cache.get(block_code)
        if not block:
            block = Block.objects.create(code=block_code, name="")
            block_cache[block_code] = block
        floor_plan = FloorPlan.objects.filter(block=block, number=floor_number).first()
        if not floor_plan:
            dims = _get_dims(floor_number)
            floor_plan = FloorPlan.objects.create(
                block=block,
                number=floor_number,
                name=f"Floor {floor_number}",
                grid_rows=dims["rows"],
                grid_cols=dims["cols"],
                blocked_cells=[],
                is_active=True,
            )
        floor_cache[key] = floor_plan
        return floor_plan

    for scan in Scan.objects.all().iterator():
        if scan.floor_plan_id:
            continue
        floor_plan = get_floor_plan(scan.block, scan.floor)
        scan.floor_plan = floor_plan
        if scan.cell_id is None:
            scan.cell_id = int(scan.cell_y) * int(floor_plan.grid_cols) + int(scan.cell_x)
        scan.save(update_fields=["floor_plan", "cell_id"])

    for aggregate in CellAggregate.objects.all().iterator():
        if aggregate.floor_plan_id:
            continue
        floor_plan = get_floor_plan(aggregate.block, aggregate.floor)
        aggregate.floor_plan = floor_plan
        aggregate.save(update_fields=["floor_plan"])


class Migration(migrations.Migration):
    dependencies = [
        ("heatmap", "0005_cellaggregate_blocked_cells"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="scan",
            name="heatmap_sca_block_a9a62e_idx",
        ),
        migrations.RemoveIndex(
            model_name="scan",
            name="heatmap_sca_cell_x_918559_idx",
        ),
        migrations.RemoveConstraint(
            model_name="cellaggregate",
            name="uniq_cellaggregate_key",
        ),
        migrations.RemoveIndex(
            model_name="cellaggregate",
            name="heatmap_cel_block_52f0bb_idx",
        ),
        migrations.RemoveIndex(
            model_name="cellaggregate",
            name="heatmap_cel_cell_x_03b6b7_idx",
        ),
        migrations.AddField(
            model_name="scan",
            name="floor_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="scans",
                to="heatmap.floorplan",
            ),
        ),
        migrations.AddField(
            model_name="scan",
            name="cell_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cellaggregate",
            name="floor_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="aggregates",
                to="heatmap.floorplan",
            ),
        ),
        migrations.RunPython(forward_fill_floor_plans, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="scan",
            name="floor_plan",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="scans",
                to="heatmap.floorplan",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="cell_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cellaggregate",
            name="floor_plan",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="aggregates",
                to="heatmap.floorplan",
            ),
        ),
        migrations.RemoveField(
            model_name="scan",
            name="block",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="cellaggregate",
            name="block",
        ),
        migrations.RemoveField(
            model_name="cellaggregate",
            name="floor",
        ),
        migrations.AddConstraint(
            model_name="cellaggregate",
            constraint=models.UniqueConstraint(
                fields=(
                    "floor_plan",
                    "cell_x",
                    "cell_y",
                    "mode",
                    "service_provider",
                    "is_all_providers",
                ),
                name="uniq_cellaggregate_key",
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["floor_plan", "mode"], name="heatmap_sca_floor_p_4e0b83_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["cell_x", "cell_y"], name="heatmap_sca_cell_x_918559_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["cell_id"], name="heatmap_sca_cell_i_3bcb1f_idx"),
        ),
        migrations.AddIndex(
            model_name="cellaggregate",
            index=models.Index(fields=["floor_plan", "mode", "is_all_providers"], name="heatmap_cel_floor_p_5b38e4_idx"),
        ),
        migrations.AddIndex(
            model_name="cellaggregate",
            index=models.Index(fields=["cell_x", "cell_y"], name="heatmap_cel_cell_x_03b6b7_idx"),
        ),
        migrations.AddIndex(
            model_name="cellaggregate",
            index=models.Index(fields=["cell_id"], name="heatmap_cel_cell_i_4e7e0c_idx"),
        ),
    ]
