# Generated by Django 5.2.12 on 2026-04-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0007_service_provider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cellaggregate',
            options={'ordering': ['floor_plan__block__code', 'floor_plan__number', 'cell_y', 'cell_x']},
        ),
        migrations.RenameIndex(
            model_name='cellaggregate',
            new_name='heatmap_cel_floor_p_5a85a2_idx',
            old_name='heatmap_cel_floor_p_5b38e4_idx',
        ),
        migrations.RenameIndex(
            model_name='cellaggregate',
            new_name='heatmap_cel_cell_x_b89462_idx',
            old_name='heatmap_cel_cell_x_03b6b7_idx',
        ),
        migrations.RenameIndex(
            model_name='cellaggregate',
            new_name='heatmap_cel_cell_id_58e069_idx',
            old_name='heatmap_cel_cell_i_4e7e0c_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='heatmap_sca_floor_p_f5a7d6_idx',
            old_name='heatmap_sca_floor_p_4e0b83_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='heatmap_sca_cell_id_ed4350_idx',
            old_name='heatmap_sca_cell_i_3bcb1f_idx',
        ),
    ]
