# Generated by Django 5.2.12 on 2026-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heatmap", "0008_alter_cellaggregate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellaggregate",
            name="signal_variance",
            field=models.FloatField(default=0),
        ),
    ]
