# Generated by Django 5.2.12 on 2026-05-01 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0013_membership_can_scan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_preset', models.CharField(choices=[('my_institution', 'My Institution'), ('best_provider', 'Best Provider'), ('weak_zones', 'Weak Zones'), ('custom', 'Custom')], default='my_institution', max_length=24)),
                ('compare_block', models.CharField(blank=True, max_length=20)),
                ('compare_floor', models.PositiveIntegerField(blank=True, null=True)),
                ('weak_threshold', models.IntegerField(default=-80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_preferences', to='heatmap.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
