# Generated by Django 5.2.11 on 2026-03-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scan',
            new_name='heatmap_sca_block_a9a62e_idx',
            old_name='heatmap_scan_block_f_c4a8fc_idx',
        ),
        migrations.RenameIndex(
            model_name='scan',
            new_name='heatmap_sca_cell_x_918559_idx',
            old_name='heatmap_scan_cell_x_ef1f9b_idx',
        ),
    ]
