# Generated by Django 5.0 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heatmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="service_provider",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
