# Generated by Django 5.2.11 on 2026-03-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatmap', '0002_rename_heatmap_scan_block_f_c4a8fc_idx_heatmap_sca_block_a9a62e_idx_and_more'),
        ('heatmap', '0002_scan_service_provider'),
    ]

    operations = [
    ]
