# Generated by Django 5.0 on 2026-03-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heatmap", "0003_merge_20260302_1111"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FloorPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.PositiveIntegerField()),
                ("name", models.CharField(blank=True, max_length=120)),
                ("grid_rows", models.PositiveIntegerField(default=12)),
                ("grid_cols", models.PositiveIntegerField(default=8)),
                ("image", models.ImageField(blank=True, upload_to="floor_maps/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "block",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="floors", to="heatmap.block"),
                ),
            ],
            options={
                "ordering": ["block__code", "number"],
            },
        ),
        migrations.AddConstraint(
            model_name="floorplan",
            constraint=models.UniqueConstraint(fields=("block", "number"), name="uniq_floorplan_block_number"),
        ),
    ]
