# Generated by Django 6.0.2 on 2026-02-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_floor_cols_alter_floor_image_alter_floor_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRawMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('network_type', models.CharField(max_length=10)),
                ('signal_strength', models.IntegerField()),
                ('device_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floor')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRawWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ssid', models.CharField(max_length=255)),
                ('bssid', models.CharField(max_length=255)),
                ('rssi', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('device_id', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.block')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floor')),
            ],
        ),
    ]
