# Generated by Django 6.0.2 on 2026-02-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRawMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('provider', models.CharField(max_length=50)),
                ('network_type', models.CharField(max_length=10)),
                ('signal_strength', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floor')),
            ],
        ),
        migrations.CreateModel(
            name='ScanRawWiFi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.IntegerField()),
                ('ssid', models.CharField(max_length=100)),
                ('bssid', models.CharField(max_length=50)),
                ('rssi', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.floor')),
            ],
        ),
    ]
