# Generated by Django 6.0.2 on 2026-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='cols',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='floor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='floor_images/'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='rows',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
